# Generated by Django 5.0.7 on 2024-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='step_required_time',
            field=models.DurationField(),
        ),
    ]
