# Generated by Django 5.0.7 on 2024-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedetail', '0005_alter_review_review_author_guid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_category',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
