# Generated by Django 5.0.7 on 2024-08-14 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipedetail', '0006_remove_ingredient_ingredient_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_interaction_liked', models.IntegerField(null=True)),
                ('rev_interaction_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipedetail.review')),
                ('rev_interaction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rev_interaction_review', 'rev_interaction_user')},
            },
        ),
    ]
