# Generated by Django 5.0.7 on 2024-08-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipedetail', '0007_reviewinteraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewinteraction',
            old_name='rev_interaction_liked',
            new_name='interaction_liked',
        ),
    ]
