# Generated by Django 5.1 on 2024-09-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipedetail', '0008_rename_rev_interaction_liked_reviewinteraction_interaction_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='step_image',
        ),
    ]
