# Generated by Django 5.0.7 on 2024-07-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=50)),
                ('quiz_difficulty', models.IntegerField()),
                ('quiz_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_sequential', models.IntegerField()),
                ('question_correct_answer', models.IntegerField()),
                ('question_possible_answers', models.JSONField()),
                ('question_quiz_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'unique_together': {('question_quiz_guid', 'question_sequential')},
            },
        ),
    ]
