# Generated by Django 5.0.7 on 2024-07-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizquestion_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_creation_date',
            field=models.DateField(null=True),
        ),
    ]
