# Generated by Django 5.1 on 2024-08-31 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user_profile_pic', models.TextField(null=True)),
                ('reg_user_about', models.CharField(max_length=200, null=True)),
                ('reg_user_search_history', models.JSONField(default={'ingredients': [], 'recipes': [], 'tags': []})),
                ('reg_user_status', models.JSONField(default={'is_suspended': False, 'notifications': [], 'suspension_end': None})),
                ('reg_user_warning_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
