# Generated by Django 5.0.7 on 2024-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_user_guid', models.UUIDField()),
                ('reg_user_name', models.CharField(max_length=50)),
                ('reg_user_surname', models.CharField(max_length=50)),
                ('reg_user_username', models.CharField(max_length=50, unique=True)),
                ('reg_user_password', models.TextField()),
                ('reg_user_email', models.EmailField(max_length=254)),
                ('reg_user_profile_pic', models.TextField()),
                ('reg_user_about', models.CharField(max_length=200)),
                ('reg_user_preferences', models.JSONField()),
                ('reg_user_status', models.JSONField()),
                ('reg_user_warning_count', models.IntegerField()),
            ],
        ),
    ]
