# Generated by Django 5.0.7 on 2024-07-25 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_registereduser_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_email',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_guid',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_password',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_surname',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='reg_user_username',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_about',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_preferences',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_profile_pic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_status',
            field=models.JSONField(default={'is_suspended': False, 'suspension_end': None}),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
