# Generated by Django 5.0.7 on 2024-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_registereduser_reg_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_status',
            field=models.JSONField(default={'is_suspended': False, 'notifications': None, 'suspension_end': None}),
        ),
    ]
