# Generated by Django 5.0.7 on 2024-08-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_registereduser_reg_user_search_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='reg_user_status',
            field=models.JSONField(default={'is_suspended': False, 'notifications': [], 'suspension_end': None}),
        ),
    ]
