# Generated by Django 5.0.7 on 2024-08-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_registereduser_reg_user_search_history_and_more'),
        ('login', '0006_alter_registereduser_reg_user_status'),
    ]

    operations = [
    ]
