# Generated by Django 5.0.7 on 2024-07-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_remove_registereduser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('fthread_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('fthread_title', models.CharField(max_length=150)),
                ('fthread_creation_date', models.DateField()),
                ('fthread_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.registereduser')),
            ],
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmessage_creation_date', models.DateField()),
                ('fmessage_up_votes', models.IntegerField()),
                ('fmessage_down_votes', models.IntegerField()),
                ('fmessage_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.registereduser')),
                ('fmessage_thread_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumthread')),
            ],
            options={
                'unique_together': {('fmessage_thread_guid', 'fmessage_creation_date', 'fmessage_author')},
            },
        ),
    ]
