# Generated by Django 5.0.7 on 2024-08-01 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forummessage_fmessage_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessage',
            name='fmessage_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='fmessage_down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forummessage',
            name='fmessage_up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForumMessageInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_liked', models.IntegerField()),
                ('interaction_fmessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forummessage')),
                ('interaction_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
