# Generated by Django 5.0.7 on 2024-07-17 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_guid', models.UUIDField()),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_prep_time', models.TimeField()),
                ('recipe_cover', models.TextField()),
                ('recipe_notes', models.CharField(max_length=500)),
                ('recipe_description', models.CharField(max_length=100)),
                ('recipe_category', models.TextField()),
                ('recipe_is_private', models.BooleanField()),
                ('recipe_is_vegetarian', models.BooleanField()),
                ('recipe_gluten_free', models.BooleanField()),
                ('recipe_is_vegan', models.BooleanField()),
                ('recipe_creation_date', models.DateField(default=None)),
                ('recipe_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.registereduser')),
            ],
        ),
    ]
