# Generated by Django 5.0.7 on 2024-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_field', models.CharField(max_length=50)),
                ('tag_relevance', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_guid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
