# Generated by Django 5.0.7 on 2024-07-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_recipe_recipe_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagXRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txr_recipe_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.recipe')),
                ('txr_tag_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.tag')),
            ],
            options={
                'unique_together': {('txr_recipe_guid', 'txr_tag_guid')},
            },
        ),
    ]
