# Generated by Django 5.0.7 on 2024-07-25 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_tagxrecipe'),
        ('login', '0003_remove_registereduser_reg_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.registereduser'),
        ),
    ]
