# Generated by Django 5.0.7 on 2024-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_recipe_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_cover',
            field=models.TextField(null=True),
        ),
    ]
