# Generated by Django 5.0.7 on 2024-07-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesCollection',
            fields=[
                ('collection_guid', models.UUIDField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=150)),
                ('collection_cover', models.TextField()),
                ('collection_creation_date', models.DateField()),
                ('collection_is_private', models.BooleanField()),
                ('collection_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.registereduser')),
            ],
        ),
    ]
