# Generated by Django 5.0.7 on 2024-08-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectionz', '0002_alter_recipescollection_collection_author'),
        ('homepage', '0008_alter_recipe_recipe_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeXCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxc_collection_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collectionz.recipescollection')),
                ('rxc_recipe_guid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.recipe')),
            ],
            options={
                'unique_together': {('rxc_collection_guid', 'rxc_recipe_guid')},
            },
        ),
    ]
